# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/beetroot',
                'doc_host': 'https://spather.github.io',
                'git_url': 'https://github.com/spather/beetroot',
                'lib_path': 'beetroot'},
  'syms': {'beetroot.core': {'beetroot.core.foo': ('core.html#foo', 'beetroot/core.py')}}}
