# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_api.ipynb.

# %% auto 0
__all__ = ['export_notebook']

# %% ../nbs/02_api.ipynb 4
import io
from IPython.display import Markdown
import json
import os
from pathlib import Path
from typing import Dict

# %% ../nbs/02_api.ipynb 5
from .source import emit_markdown_source, emit_python_source
from beetroot.outputs import (
    emit_display_data_output,
    emit_execute_result_output,
    emit_stream_output,
)

# %% ../nbs/02_api.ipynb 6
def export_notebook(nb_json: Dict) -> str:
    stream = io.StringIO()
    for cell in nb_json["cells"]:
        if cell["cell_type"] == "markdown":
            emit_markdown_source(cell["source"], stream)
            stream.write("\n")
        elif cell["cell_type"] == "code":
            emit_python_source(cell["source"], stream)
            stream.write("\n")

            for output in cell["outputs"]:
                output_type = output["output_type"]
                if output_type == "stream":
                    emit_stream_output(output, stream)
                elif output_type == "display_data":
                    emit_display_data_output(output, stream)
                elif output_type == "execute_result":
                    emit_execute_result_output(output, stream)
                stream.write("\n")

    stream.seek(0)
    return stream.read()
