# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_api.ipynb.

# %% auto 0
__all__ = ['export_notebook']

# %% ../nbs/03_api.ipynb 5
import io
from typing import Dict, List, Iterable, Reversible, Sequence, Tuple

# %% ../nbs/03_api.ipynb 6
from .transformations import Transformer
from beetroot.source import (
    SourceHandler,
)
from beetroot.outputs import (
    Completion,
    OutputHandler,
)

# %% ../nbs/03_api.ipynb 7
def export_notebook(
    nb_json: Dict, transformers_map: Dict[str, Reversible[Transformer]] = {}
) -> Tuple[str, Iterable[Completion]]:
    stream = io.StringIO()
    source_handler = SourceHandler(stream, transformers_map)
    output_handler = OutputHandler(stream, transformers_map)

    completions: List[Completion] = []
    for cell in nb_json["cells"]:
        if cell["cell_type"] == "markdown":
            source_handler.emit_markdown(cell["source"])
            stream.write("\n")
        elif cell["cell_type"] == "code":
            did_echo, should_show_output = source_handler.emit_python_source(
                cell["source"]
            )
            if did_echo:
                stream.write("\n")

            if not should_show_output:
                continue

            for output in cell["outputs"]:
                completions.extend(output_handler.handle_output(output))
                stream.write("\n")

    stream.seek(0)
    return stream.read(), completions
