# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_backend_config.ipynb.

# %% auto 0
__all__ = ['BackendConfig']

# %% ../nbs/01_backend_config.ipynb 4
import argparse
from typing import Dict, Protocol

# %% ../nbs/01_backend_config.ipynb 5
class BackendConfig(Protocol):
    def configure_arg_parser(self, parser: argparse.ArgumentParser):
        """Configure the given argument parser with the arguments\
            required by this backend."""
        pass

    def run(self, nb_json: Dict, args: argparse.Namespace):
        """Run the backend with the given notebook JSON and args."""
        pass
