# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_cli.ipynb.

# %% auto 0
__all__ = ['br_export']

# %% ../nbs/02_cli.ipynb 4
import argparse
import json
from pathlib import Path
from typing import Dict, Protocol

# %% ../nbs/02_cli.ipynb 5
from beetroot.markdown.cli import MarkdownBackendConfig

# %% ../nbs/02_cli.ipynb 6
backends_map = {
    "markdown": MarkdownBackendConfig(),
}

# %% ../nbs/02_cli.ipynb 7
def br_export():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "nb_filename", type=str, help="Full path to the notebook to export"
    )
    parser.add_argument(
        "--backend",
        choices=backends_map.keys(),
        default="markdown",
        help="The backend to use",
    )

    # Parse the known args, to determine what the backend is
    args, _ = parser.parse_known_args()

    # Get the backend config based on its name and use it to configure the
    # rest of args parsing.
    backend_config = backends_map[args.backend]
    backend_config.configure_arg_parser(parser)
    args = parser.parse_args()

    # Load the JSON
    nb_json = json.loads(Path(args.nb_filename).read_text())

    # Run the backend
    backend_config.run(nb_json, args)
