# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_cli.ipynb.

# %% auto 0
__all__ = ['br_export']

# %% ../nbs/03_cli.ipynb 3
import argparse
import json
from pathlib import Path

from .api import export_notebook

# %% ../nbs/03_cli.ipynb 4
def br_export():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "nb_filename", type=str, help="Full path to the notebook to export"
    )
    args = parser.parse_args()

    nb_json = json.loads(Path(args.nb_filename).read_text())
    markdown = export_notebook(nb_json)
    print(markdown)
