# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_source.ipynb.

# %% auto 0
__all__ = ['emit_python_source', 'emit_markdown_source']

# %% ../nbs/00_source.ipynb 4
import io
from typing import Iterable

# %% ../nbs/00_source.ipynb 5
def emit_python_source(source: Iterable[str], stream: io.TextIOBase):
    stream.write("```python\n")
    for line in source:
        stream.write(line)
    stream.write("\n```\n\n")

# %% ../nbs/00_source.ipynb 7
def emit_markdown_source(markdown: Iterable[str], stream: io.TextIOBase):
    for line in markdown:
        stream.write(line)
    stream.write("\n")
